work on navBar
kaushaki-kumari/PollingApp pull request #4
Opened 2024-12-27 11:12 UTC by kaushaki-kumari

2025-01-02 05:17 UTC, meanstack9716 requested changes

2025-01-02 05:17 UTC, meanstack9716 commented on src/App.jsx
> +import Poll_Page from "./pages/Poll_Page.jsx";
shuld not include _ @kaushaki-kumari

2025-01-02 05:17 UTC, meanstack9716 commented on src/app/store.js
> +import pollReducer from "../features/pollSlice";
create a folder name reducer and move all reduces into that, not in a features folder @kaushaki-kumari

2025-01-03 11:47 UTC, yuvrajInno commented on src/utils/constant.js
> +export const LIMIT = 10;
What limit what page no?

2025-01-03 11:48 UTC, yuvrajInno commented on src/utils/axiosInstance.js
> +  (error) => {
add condition here if we get 403 status error the user should logout

2025-01-03 11:50 UTC, yuvrajInno commented on src/reducer/pollSlice.js
> +    currentPage: PAGE_NO,
this should be in component

2025-01-03 11:50 UTC, yuvrajInno commented on src/reducer/pollSlice.js
> +    totalPages: 1,
no need here

2025-01-03 11:58 UTC, yuvrajInno commented on src/pages/Poll_Page.jsx
> +      const storedVotes =
No need for this

2025-01-03 11:59 UTC, yuvrajInno commented on src/pages/Poll_Page.jsx
> +  const [isModalOpen, setIsModalOpen] = useState(false);
Improve variable name what modal?

2025-01-03 12:06 UTC, yuvrajInno commented on src/pages/Poll_Page.jsx
> +    const poll = polls.find((poll) => poll.id === pollId);
why do you need filter use as parameter

2025-01-03 12:07 UTC, yuvrajInno commented on src/pages/Poll_Page.jsx
> +                      <FaRegEdit className="cursor-pointer w-8 h-8" />
just add delete icon too for now

2025-01-03 12:09 UTC, yuvrajInno commented on src/components/PollResultsModal.jsx
> +  useEffect(() => {
why do you nedd this?

2025-01-06 10:00 UTC, yuvrajInno commented on src/components/DeletePollModal.jsx
> +import React from "react";
change name to deleteconfirmmodal

2025-01-06 10:01 UTC, yuvrajInno commented on src/components/DeletePollModal.jsx
> +          <h3 className="text-xl font-semibold">Delete Poll</h3>
use props

2025-01-06 10:01 UTC, yuvrajInno commented on src/components/DeletePollModal.jsx
> +        <p className="mb-4">Are you sure you want to delete this poll?</p>
here too

2025-01-06 10:03 UTC, yuvrajInno commented on src/pages/PollPage.jsx
> +import { deletePoll } from "../reducer/pollSlice";
use import from same plac

2025-01-06 10:04 UTC, yuvrajInno commented on src/pages/PollPage.jsx
> +        const uniquePolls = [...prevPolls];
what is unique poll improve naming sense and why are you doing this?

2025-01-06 10:05 UTC, yuvrajInno commented on src/pages/PollPage.jsx
> +  const [allPolls, setAllPolls] = useState([]);
use polls from reducer no need to create a new variable here too.

2025-01-06 10:07 UTC, yuvrajInno commented on src/pages/PollPage.jsx
> +  const handleSubmit = async (pollId) => {
what submit?

2025-01-06 10:09 UTC, yuvrajInno commented on src/pages/PollPage.jsx
> +      setAllPolls((prevPolls) =>
filter this in reducer

2025-01-06 10:12 UTC, yuvrajInno commented on src/reducer/pollSlice.js
> +          if (optionIndex !== -1) {
no need for this now

2025-01-06 10:13 UTC, yuvrajInno commented on src/reducer/pollSlice.js
> +        const pollIndex = state.polls.findIndex((poll) => poll.id === pollId);
we don't need to update count manually with API

2025-01-06 12:10 UTC, yuvrajInno commented on src/reducer/pollSlice.js
> +          (newPoll) =>
why are you filtering

2025-01-06 12:21 UTC, merged